import XML_TEMPLATE from '@src/templates/xmlTemplate';

/**
 * Concatenates the XML templates with or without the navigation fragment.
 * @param wrappedTemplates - The wrapped templates generated by ASTToSapui5XML.
 * @param withNavigation - If true, includes the navigation fragment in the XML.
 * @returns The full SAPUI5 XML as a string.
 */
function concatenateXML(
  wrappedTemplates: string[],
  withNavigation: boolean,
): string {
  let xmlContent = XML_TEMPLATE.top;

  if (withNavigation) {
    xmlContent +=
      XML_TEMPLATE.navTop +
      wrappedTemplates.join('\n') +
      XML_TEMPLATE.navBottom;
  } else {
    xmlContent += wrappedTemplates.join('\n');
  }

  xmlContent += XML_TEMPLATE.bottom;
  return xmlContent;
}

export default concatenateXML;
